import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from './_components/shared/Navigation';
import ThemeProvider from './_components/shared/providers/ThemeProvider';
import ClerkAppProvider from './_components/shared/providers/ClerkAppProvider';
import { Toaster } from '@/components/ui/toaster';
import ScrollToTop from './_components/shared/ScrollToTop';
import { AuthProvider } from './_context/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Collab Space',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <ThemeProvider attribute='class'>
                    <ClerkAppProvider>
                        <AuthProvider>
                            <Navigation />
                            {children}
                            <ScrollToTop />
                            <Toaster />
                        </AuthProvider>
                    </ClerkAppProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
